---

- name: Ensures contrail configuration dir exists
  file: path=/etc/contrail/ state=directory

- name: contrail analytics configuration files
  template: src=contrail/{{ item }}.conf.j2 dest=/etc/contrail/{{ item }}.conf
  with_items:
   - contrail-collector
   - contrail-query-engine
   - contrail-analytics-api
  notify: contrail analytics services restarted

