---

- name: install contrail config packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - bird

- name: contrail config services started and enabled
  service: name={{ item }} state=started enabled=yes
  with_items:
   - bird
