---

- name: install contrail config packages
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
  - contrail-config
  - contrail-utils

- name: contrail config services started and enabled
  service: name={{ item }} state=started enabled=yes
  with_items:
   - contrail-discovery
   - contrail-api
   - contrail-device-manager
   - contrail-schema
